name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.4.2
      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Test
        run: go test -timeout 1h -v ./...
