name: Auto Dependency Update

on:
  schedule:
    - cron: '0 0 * * *' # Executes daily at midnight UTC
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update dependencies
      run: |
        go get -u ./...
        go mod tidy
        git diff

    - name: Commit changes
      run: |
        git checkout -b dependency-update || git checkout dependency-update
        git add go.mod go.sum
        git commit -m "chore: update dependencies" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin dependency-update --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dependency-update
        title: "chore: update dependencies"
        body: |
          This PR updates project dependencies automatically.
        labels: |
          dependencies
